Iter5
Gerfey/shortener pull request #5
Opened 2024-10-05 07:09 UTC by Gerfey

2024-10-07 12:25 UTC, arttet requested changes
- [ ] Split the application into layers
https://github.com/golang-standards/project-layout
https://medium.com/@deanrubin/the-three-layered-architecture-fe30cb0e4a6#:~:text=The%20presentation%20layer%20is%20the,Update%20or%20Delete)%20operation%20flow.
Please integrate CodeCov https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- [ ] Please read and use the Conventional Commits specification https://www.conventionalcommits.org/en/v1.0.0/
- [ ] Please integrate the linter https://github.com/golangci/golangci-lint-action
- [ ] Please don't use global variables
- [ ] Please delete deprecated constraints in CI
https://github.com/Gerfey/shortener/blob/e90b90d0a3e871d0c4f9109ffb1b2c445448912c/.github/workflows/shortenertest.yml#L65

2024-10-07 12:25 UTC, arttet commented on cmd/shortener/flag.go
> +	flagRunServerAddress       string
[CHANGE REQUEST] Please don't use global variables

2024-10-07 12:25 UTC, arttet commented on cmd/shortener/main.go
> +	"log"
[CHANGE REQUEST] Please sort imports
https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-10-07 12:25 UTC, arttet commented on internal/app/generator/generator.go
> +type Generator interface {
[CLARIFICATION] Why do you need it?

2024-10-07 12:25 UTC, arttet commented on internal/app/store/store.go
> +type Store struct {
[CLARIFICATION] Why don't you use `interface`?

2024-10-07 12:25 UTC, arttet commented on internal/pkg/app/app.go
> +	c *config.Config
[CHANGE REQUEST] Please rename it.
https://github.com/uber-go/guide/blob/master/style.md

2024-10-07 18:23 UTC, Gerfey commented on cmd/shortener/flag.go
> +	flagRunServerAddress       string
@arttet в курсе одно, к код ревью другое?)

2024-10-07 18:23 UTC, Gerfey commented on cmd/shortener/main.go
> +	"log"
Пакеты сортируются автоматом GoLand

2024-10-08 09:34 UTC, Gerfey commented on internal/app/generator/generator.go
> +type Generator interface {
Это генератор, который будет создавать из случайной последовательности код для сокращения URL

2024-10-10 08:20 UTC, arttet approved these changes

2024-10-10 08:20 UTC, arttet commented on .github/workflows/codecov.yml
> +        uses: codecov/codecov-action@v3
```suggestion
        uses: codecov/codecov-action@v4
```

2024-10-10 08:20 UTC, arttet commented on .github/workflows/codecov.yml
> +        uses: codecov/codecov-action@v3
https://github.com/codecov/codecov-action

2024-10-10 08:20 UTC, arttet commented on .github/workflows/codecov.yml
> +        uses: codecov/codecov-action@v3
[SUGGESTION] You can use Dependabot

https://gist.github.com/magnetikonline/6f215db058e327905bce66c37f92426c

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

2024-10-10 08:20 UTC, arttet commented on internal/app/repository/repository.go
> +	Find(key string) (string, bool)
```suggestion
	FindURL(key string) (string, bool)
```

2024-10-10 08:20 UTC, arttet commented on internal/pkg/app/app.go
> +		log.Fatal(err)
[SUGGESTION] It would be better if you returned an error.

2024-10-17 13:00 UTC, merged